#!/bin/zsh

# Get the directory of the current script
SCRIPT_DIR=${0:a:h}
source "${SCRIPT_DIR}/../utils.zsh"

print_in_purple "
   WezTerm Terminal Emulator

"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Installation
execute "brew install --cask wezterm" \
    "Installing WezTerm"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Configuration Setup
WEZTERM_CONFIG_DIR="$HOME/.config/wezterm"
WEZTERM_CONFIG_FILE="$WEZTERM_CONFIG_DIR/wezterm.lua"

# Create WezTerm config directory
if [[ ! -d "$WEZTERM_CONFIG_DIR" ]]; then
    mkdir -p "$WEZTERM_CONFIG_DIR"
    print_success "Created WezTerm config directory: $WEZTERM_CONFIG_DIR"
fi

# Create WezTerm configuration file
if [[ ! -f "$WEZTERM_CONFIG_FILE" ]]; then
    cat > "$WEZTERM_CONFIG_FILE" << 'EOF'
-- WezTerm Configuration
-- This file is automatically generated by the dots setup

local wezterm = require 'wezterm'
local config = {}

-- General settings
config.color_scheme = 'Catppuccin Mocha'
config.font = wezterm.font('JetBrains Mono', { weight = 'Medium' })
config.font_size = 12.0
config.line_height = 1.0
config.cell_width = 1.0
config.cell_height = 1.0

-- Window settings
config.window_decorations = "RESIZE"
config.window_padding = {
    left = 8,
    right = 8,
    top = 8,
    bottom = 8,
}
config.window_background_opacity = 0.95
config.macos_window_background_blur = 20

-- Tab bar settings
config.tab_bar_at_bottom = true
config.use_fancy_tab_bar = true
config.show_tabs_in_tab_bar = true
config.show_new_tab_button_in_tab_bar = true
config.tab_max_width = 32
config.hide_tab_bar_if_only_one_tab = false

-- Cursor settings
config.default_cursor_style = "BlinkingBlock"
config.cursor_blink_rate = 500
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- Scrollback settings
config.scrollback_lines = 10000
config.enable_scroll_bar = true

-- Selection settings
config.selection_word_boundary = " \t\n{}[]()\"'`"

-- Bell settings
config.audible_bell = "SystemBeep"
config.visual_bell = {
    fade_in_function = "EaseIn",
    fade_in_duration_ms = 150,
    fade_out_function = "EaseOut",
    fade_out_duration_ms = 150,
}

-- Key bindings
config.keys = {
    -- Copy and paste
    {
        key = 'c',
        mods = 'CMD',
        action = wezterm.action.CopyTo 'Clipboard',
    },
    {
        key = 'v',
        mods = 'CMD',
        action = wezterm.action.PasteFrom 'Clipboard',
    },
    -- New tab
    {
        key = 't',
        mods = 'CMD',
        action = wezterm.action.SpawnTab 'CurrentPaneDomain',
    },
    -- Close tab
    {
        key = 'w',
        mods = 'CMD',
        action = wezterm.action.CloseCurrentTab { confirm = true },
    },
    -- Split pane horizontally
    {
        key = 'd',
        mods = 'CMD|SHIFT',
        action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' },
    },
    -- Split pane vertically
    {
        key = 'd',
        mods = 'CMD',
        action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' },
    },
    -- Close pane
    {
        key = 'w',
        mods = 'CMD|SHIFT',
        action = wezterm.action.CloseCurrentPane { confirm = true },
    },
    -- Navigate between panes
    {
        key = 'LeftArrow',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ActivatePaneDirection 'Left',
    },
    {
        key = 'RightArrow',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ActivatePaneDirection 'Right',
    },
    {
        key = 'UpArrow',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ActivatePaneDirection 'Up',
    },
    {
        key = 'DownArrow',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ActivatePaneDirection 'Down',
    },
    -- Resize panes
    {
        key = 'H',
        mods = 'CMD|SHIFT',
        action = wezterm.action.AdjustPaneSize { 'Left', 5 },
    },
    {
        key = 'L',
        mods = 'CMD|SHIFT',
        action = wezterm.action.AdjustPaneSize { 'Right', 5 },
    },
    {
        key = 'K',
        mods = 'CMD|SHIFT',
        action = wezterm.action.AdjustPaneSize { 'Up', 5 },
    },
    {
        key = 'J',
        mods = 'CMD|SHIFT',
        action = wezterm.action.AdjustPaneSize { 'Down', 5 },
    },
    -- Zoom pane
    {
        key = 'z',
        mods = 'CMD',
        action = wezterm.action.TogglePaneZoomState,
    },
    -- Full screen
    {
        key = 'Enter',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ToggleFullScreen,
    },
    -- Reload config
    {
        key = 'r',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ReloadConfiguration,
    },
    -- Show launcher
    {
        key = 'p',
        mods = 'CMD|SHIFT',
        action = wezterm.action.ShowLauncher,
    },
}

-- Mouse bindings
config.mouse_bindings = {
    -- Right click to paste
    {
        event = { Down = { streak = 1, button = 'Right' } },
        mods = 'NONE',
        action = wezterm.action.PasteFrom 'Clipboard',
    },
    -- Scroll wheel to scroll
    {
        event = { Down = { streak = 1, button = 'WheelUp' } },
        mods = 'NONE',
        action = wezterm.action.ScrollByLine(-3),
    },
    {
        event = { Down = { streak = 1, button = 'WheelDown' } },
        mods = 'NONE',
        action = wezterm.action.ScrollByLine(3),
    },
}

-- Color schemes
config.color_schemes = {
    ['Catppuccin Mocha'] = {
        background = '#1e1e2e',
        foreground = '#cdd6f4',
        cursor_bg = '#f5e0dc',
        cursor_border = '#f5e0dc',
        cursor_fg = '#1e1e2e',
        selection_bg = '#585b70',
        selection_fg = '#cdd6f4',
        ansi = {
            '#45475a', -- black
            '#f38ba8', -- red
            '#a6e3a1', -- green
            '#f9e2af', -- yellow
            '#89b4fa', -- blue
            '#f5c2e7', -- magenta
            '#94e2d5', -- cyan
            '#bac2de', -- white
        },
        brights = {
            '#585b70', -- bright black
            '#f38ba8', -- bright red
            '#a6e3a1', -- bright green
            '#f9e2af', -- bright yellow
            '#89b4fa', -- bright blue
            '#f5c2e7', -- bright magenta
            '#94e2d5', -- bright cyan
            '#a6adc8', -- bright white
        },
    },
    ['Gruvbox Dark'] = {
        background = '#282828',
        foreground = '#ebdbb2',
        cursor_bg = '#ebdbb2',
        cursor_border = '#ebdbb2',
        cursor_fg = '#282828',
        selection_bg = '#458588',
        selection_fg = '#ebdbb2',
        ansi = {
            '#282828', -- black
            '#cc241d', -- red
            '#98971a', -- green
            '#d79921', -- yellow
            '#458588', -- blue
            '#b16286', -- magenta
            '#689d6a', -- cyan
            '#a89984', -- white
        },
        brights = {
            '#928374', -- bright black
            '#fb4934', -- bright red
            '#b8bb26', -- bright green
            '#fabd2f', -- bright yellow
            '#83a598', -- bright blue
            '#d3869b', -- bright magenta
            '#8ec07c', -- bright cyan
            '#ebdbb2', -- bright white
        },
    },
    ['Nord'] = {
        background = '#2e3440',
        foreground = '#d8dee9',
        cursor_bg = '#d8dee9',
        cursor_border = '#d8dee9',
        cursor_fg = '#2e3440',
        selection_bg = '#4c566a',
        selection_fg = '#d8dee9',
        ansi = {
            '#3b4252', -- black
            '#bf616a', -- red
            '#a3be8c', -- green
            '#ebcb8b', -- yellow
            '#81a1c1', -- blue
            '#b48ead', -- magenta
            '#88c0d0', -- cyan
            '#e5e9f0', -- white
        },
        brights = {
            '#4c566a', -- bright black
            '#bf616a', -- bright red
            '#a3be8c', -- bright green
            '#ebcb8b', -- bright yellow
            '#81a1c1', -- bright blue
            '#b48ead', -- bright magenta
            '#8fbcbb', -- bright cyan
            '#eceff4', -- bright white
        },
    },
}

-- Default color scheme
config.color_scheme = 'Catppuccin Mocha'

-- Tab bar colors
config.colors = {
    tab_bar = {
        background = '#1e1e2e',
        active_tab = {
            bg_color = '#89b4fa',
            fg_color = '#1e1e2e',
        },
        inactive_tab = {
            bg_color = '#45475a',
            fg_color = '#cdd6f4',
        },
        inactive_tab_hover = {
            bg_color = '#585b70',
            fg_color = '#cdd6f4',
        },
        new_tab = {
            bg_color = '#45475a',
            fg_color = '#cdd6f4',
        },
        new_tab_hover = {
            bg_color = '#585b70',
            fg_color = '#cdd6f4',
        },
    },
}

-- Launch menu
config.launch_menu = {
    {
        label = 'zsh',
        args = { 'zsh' },
    },
    {
        label = 'bash',
        args = { 'bash' },
    },
    {
        label = 'fish',
        args = { 'fish' },
    },
    {
        label = 'tmux',
        args = { 'tmux' },
    },
}

-- Set default shell
config.default_prog = { 'zsh' }

-- Enable CSI u mode for better keyboard support
config.enable_csi_u_key_encoding = true

-- Disable ligatures by default (can be enabled per font)
config.harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' }

-- Window title
config.window_title = 'WezTerm'

-- Enable tab bar
config.show_tab_bar = true

-- Tab bar style
config.use_fancy_tab_bar = true
config.tab_bar_at_bottom = true

-- Tab bar colors
config.colors.tab_bar = {
    background = '#1e1e2e',
    active_tab = {
        bg_color = '#89b4fa',
        fg_color = '#1e1e2e',
    },
    inactive_tab = {
        bg_color = '#45475a',
        fg_color = '#cdd6f4',
    },
    inactive_tab_hover = {
        bg_color = '#585b70',
        fg_color = '#cdd6f4',
    },
    new_tab = {
        bg_color = '#45475a',
        fg_color = '#cdd6f4',
    },
    new_tab_hover = {
        bg_color = '#585b70',
        fg_color = '#cdd6f4',
    },
}

-- Return the config
return config
EOF

    print_success "Created WezTerm configuration file: $WEZTERM_CONFIG_FILE"
else
    print_success "WezTerm configuration file already exists: $WEZTERM_CONFIG_FILE"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Color Schemes
WEZTERM_COLORS_DIR="$WEZTERM_CONFIG_DIR/colors"

if [[ ! -d "$WEZTERM_COLORS_DIR" ]]; then
    mkdir -p "$WEZTERM_COLORS_DIR"
    print_success "Created WezTerm colors directory: $WEZTERM_COLORS_DIR"
fi

# Create additional color schemes
cat > "$WEZTERM_COLORS_DIR/dracula.lua" << 'EOF'
-- Dracula color scheme for WezTerm
return {
    foreground = '#f8f8f2',
    background = '#282a36',
    cursor_bg = '#f8f8f2',
    cursor_border = '#f8f8f2',
    cursor_fg = '#282a36',
    selection_bg = '#44475a',
    selection_fg = '#f8f8f2',
    ansi = {
        '#282a36', -- black
        '#ff5555', -- red
        '#50fa7b', -- green
        '#f1fa8c', -- yellow
        '#bd93f9', -- blue
        '#ff79c6', -- magenta
        '#8be9fd', -- cyan
        '#f8f8f2', -- white
    },
    brights = {
        '#6272a4', -- bright black
        '#ff6e6e', -- bright red
        '#69ff94', -- bright green
        '#ffffa5', -- bright yellow
        '#d6acff', -- bright blue
        '#ff92df', -- bright magenta
        '#a4ffff', -- bright cyan
        '#ffffff', -- bright white
    },
}
EOF

cat > "$WEZTERM_COLORS_DIR/tokyonight.lua" << 'EOF'
-- Tokyo Night color scheme for WezTerm
return {
    foreground = '#c0caf5',
    background = '#1a1b26',
    cursor_bg = '#c0caf5',
    cursor_border = '#c0caf5',
    cursor_fg = '#1a1b26',
    selection_bg = '#33467c',
    selection_fg = '#c0caf5',
    ansi = {
        '#15161e', -- black
        '#f7768e', -- red
        '#9ece6a', -- green
        '#e0af68', -- yellow
        '#7aa2f7', -- blue
        '#bb9af7', -- magenta
        '#7dcfff', -- cyan
        '#a9b1d6', -- white
    },
    brights = {
        '#414868', -- bright black
        '#f7768e', -- bright red
        '#9ece6a', -- bright green
        '#e0af68', -- bright yellow
        '#7aa2f7', -- bright blue
        '#bb9af7', -- bright magenta
        '#7dcfff', -- bright cyan
        '#c0caf5', -- bright white
    },
}
EOF

print_success "Created additional WezTerm color schemes"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Fonts Configuration
WEZTERM_FONTS_DIR="$WEZTERM_CONFIG_DIR/fonts"

if [[ ! -d "$WEZTERM_FONTS_DIR" ]]; then
    mkdir -p "$WEZTERM_FONTS_DIR"
    print_success "Created WezTerm fonts directory: $WEZTERM_FONTS_DIR"
fi

# Create font configuration
cat > "$WEZTERM_FONTS_DIR/config.lua" << 'EOF'
-- Font configuration for WezTerm
local wezterm = require 'wezterm'

local fonts = {
    -- Primary font
    primary = wezterm.font('JetBrains Mono', { weight = 'Medium' }),

    -- Alternative fonts
    alternatives = {
        wezterm.font('Fira Code', { weight = 'Medium' }),
        wezterm.font('Source Code Pro', { weight = 'Medium' }),
        wezterm.font('Monaco'),
        wezterm.font('Menlo'),
        wezterm.font('Consolas'),
    },

    -- Font with ligatures
    with_ligatures = wezterm.font('JetBrains Mono', {
        weight = 'Medium',
        harfbuzz_features = { 'calt=1', 'clig=1', 'liga=1' }
    }),
}

return fonts
EOF

print_success "Created WezTerm font configuration"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Themes Configuration
WEZTERM_THEMES_DIR="$WEZTERM_CONFIG_DIR/themes"

if [[ ! -d "$WEZTERM_THEMES_DIR" ]]; then
    mkdir -p "$WEZTERM_THEMES_DIR"
    print_success "Created WezTerm themes directory: $WEZTERM_THEMES_DIR"
fi

# Create theme configuration
cat > "$WEZTERM_THEMES_DIR/config.lua" << 'EOF'
-- Theme configuration for WezTerm
local themes = {
    dark = {
        color_scheme = 'Catppuccin Mocha',
        window_background_opacity = 0.95,
    },
    light = {
        color_scheme = 'Gruvbox Light',
        window_background_opacity = 0.98,
    },
    transparent = {
        color_scheme = 'Catppuccin Mocha',
        window_background_opacity = 0.85,
        macos_window_background_blur = 30,
    },
    minimal = {
        color_scheme = 'Nord',
        window_background_opacity = 1.0,
        tab_bar_at_bottom = false,
        use_fancy_tab_bar = false,
    },
}

return themes
EOF

print_success "Created WezTerm theme configuration"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Keybindings Configuration
WEZTERM_KEYBINDINGS_FILE="$WEZTERM_CONFIG_DIR/keybindings.lua"

cat > "$WEZTERM_KEYBINDINGS_FILE" << 'EOF'
-- Additional keybindings for WezTerm
local wezterm = require 'wezterm'

local keybindings = {
    -- Development shortcuts
    {
        key = 'g',
        mods = 'CMD',
        action = wezterm.action.SpawnCommandInNewTab {
            cwd = '~',
        },
    },
    {
        key = 'n',
        mods = 'CMD|SHIFT',
        action = wezterm.action.SpawnWindow,
    },
    -- Quick theme switching
    {
        key = '1',
        mods = 'CMD|SHIFT',
        action = wezterm.action_callback(function(window, pane)
            window:perform_action(
                wezterm.action.SetColorScheme 'Catppuccin Mocha',
                pane
            )
        end),
    },
    {
        key = '2',
        mods = 'CMD|SHIFT',
        action = wezterm.action_callback(function(window, pane)
            window:perform_action(
                wezterm.action.SetColorScheme 'Nord',
                pane
            )
        end),
    },
    {
        key = '3',
        mods = 'CMD|SHIFT',
        action = wezterm.action_callback(function(window, pane)
            window:perform_action(
                wezterm.action.SetColorScheme 'Gruvbox Dark',
                pane
            )
        end),
    },
    -- Font size adjustments
    {
        key = '+',
        mods = 'CMD',
        action = wezterm.action.IncreaseFontSize,
    },
    {
        key = '-',
        mods = 'CMD',
        action = wezterm.action.DecreaseFontSize,
    },
    {
        key = '0',
        mods = 'CMD',
        action = wezterm.action.ResetFontSize,
    },
}

return keybindings
EOF

print_success "Created WezTerm keybindings configuration"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Tab Configuration
WEZTERM_TABS_FILE="$WEZTERM_CONFIG_DIR/tabs.lua"

cat > "$WEZTERM_TABS_FILE" << 'EOF'
-- Tab configuration for WezTerm
local wezterm = require 'wezterm'

local tab_config = {
    -- Tab bar appearance
    tab_bar_at_bottom = true,
    use_fancy_tab_bar = true,
    show_tabs_in_tab_bar = true,
    show_new_tab_button_in_tab_bar = true,
    tab_max_width = 32,
    hide_tab_bar_if_only_one_tab = false,

    -- Tab colors
    colors = {
        tab_bar = {
            background = '#1e1e2e',
            active_tab = {
                bg_color = '#89b4fa',
                fg_color = '#1e1e2e',
            },
            inactive_tab = {
                bg_color = '#45475a',
                fg_color = '#cdd6f4',
            },
            inactive_tab_hover = {
                bg_color = '#585b70',
                fg_color = '#cdd6f4',
            },
            new_tab = {
                bg_color = '#45475a',
                fg_color = '#cdd6f4',
            },
            new_tab_hover = {
                bg_color = '#585b70',
                fg_color = '#cdd6f4',
            },
        },
    },
}

return tab_config
EOF

print_success "Created WezTerm tab configuration"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# WezTerm Window Configuration
WEZTERM_WINDOWS_FILE="$WEZTERM_CONFIG_DIR/windows.lua"

cat > "$WEZTERM_WINDOWS_FILE" << 'EOF'
-- Window configuration for WezTerm
local wezterm = require 'wezterm'

local window_config = {
    -- Window appearance
    window_decorations = 'RESIZE',
    window_padding = {
        left = 8,
        right = 8,
        top = 8,
        bottom = 8,
    },
    window_background_opacity = 0.95,
    macos_window_background_blur = 20,

    -- Window behavior
    window_close_confirmation = 'AlwaysPrompt',
    confirm_before_quit = 'AlwaysPrompt',

    -- Initial window size
    initial_cols = 120,
    initial_rows = 30,

    -- Window title
    window_title = 'WezTerm',
    window_title_override = function(window, pane, title, max_width)
        return title
    end,
}

return window_config
EOF

print_success "Created WezTerm window configuration"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set environment variable for WezTerm config
export WEZTERM_CONFIG_FILE="$WEZTERM_CONFIG_FILE"

# Note: WezTerm configuration is handled by wezterm.zsh config file

print_success "WezTerm installation and configuration completed!"
print_in_green "
   WezTerm is now installed and configured with:
   - Modern terminal configuration with Catppuccin Mocha theme
   - Comprehensive keybindings for development workflow
   - Multiple color schemes (Catppuccin, Gruvbox, Nord, Dracula, Tokyo Night)
   - Font configuration with JetBrains Mono
   - Tab and window management settings
   - Environment variable setup for shell integration

   Configuration file: $WEZTERM_CONFIG_FILE
   You can customize WezTerm by editing this file.

"
