# Zsh configuration file
# Load all shell configurations
for file in ~/dots/linux/configs/shell/aliases/*; do
    if [[ -f "$file" ]]; then
        source "$file"
    fi
done

# Load zsh-specific configurations
source ~/dots/linux/configs/shell/zsh_exports
source ~/dots/linux/configs/shell/zsh_functions
source ~/dots/linux/configs/shell/zsh_options
source ~/dots/linux/configs/shell/zsh_prompt

# Load colors
source ~/dots/linux/configs/shell/colors/macos/zsh_colors

# Load autocomplete
fpath=(~/dots/linux/configs/shell/autocomplete/macos $fpath)

# Initialize autocomplete
autoload -Uz compinit
compinit

# Load other configurations
source ~/dots/linux/configs/shell/curlrc

# Load keybindings
if [[ -f ~/dots/linux/configs/shell/zsh_keybindings ]]; then
  source ~/dots/linux/configs/shell/zsh_keybindings
fi

# Load zsh_logout
if [[ -f ~/dots/linux/configs/shell/zsh_logout ]]; then
  source ~/dots/linux/configs/shell/zsh_logout
fi
